// Regenerates src/brand/marks.ts from the assets in public/brand.
// Marks must be inlined as data URIs: an SVG rasterised through an Image never
// fetches external hrefs, so the export path would produce a blank garment.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const brand = join(root, "public", "brand");

const INK_TOKEN = "__INK__";

function monoSvg(file) {
  const raw = readFileSync(join(brand, file), "utf8");
  // The committed asset carries a literal fill; swap it for a token the
  // renderer replaces with the garment's contrast colour.
  return raw.replace(/fill="#000000"/g, `fill="${INK_TOKEN}"`);
}

function rasterDataUri(file) {
  return `data:image/png;base64,${readFileSync(join(brand, file)).toString("base64")}`;
}

const out = `// GENERATED by scripts/generate-marks.mjs -- do not edit by hand.
export const INK_TOKEN = ${JSON.stringify(INK_TOKEN)};

export const MARK_COGNITION_SVG = ${JSON.stringify(monoSvg("mark-cognition.svg"))};

export const MARK_DEVIN_ON_BLACK_PNG = ${JSON.stringify(rasterDataUri("mark-devin-on-black.png"))};

export const MARK_DEVIN_ON_WHITE_PNG = ${JSON.stringify(rasterDataUri("mark-devin-on-white.png"))};

export const MARK_OTTER_PNG = ${JSON.stringify(rasterDataUri("mark-otter.png"))};
`;

writeFileSync(join(root, "src", "brand", "marks.ts"), out);
console.log("wrote src/brand/marks.ts");
